events {}

http {
  server {
    listen 80;

    location / {
#      proxy_pass http://172.16.100.1:3000;
      proxy_pass http://172.16.100.142:3000;
      # если host.docker.internal не работает на Linux - ниже скажу замену
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Снимаем запреты на iframe
      proxy_hide_header X-Frame-Options;
      proxy_hide_header Content-Security-Policy;
      add_header X-Frame-Options "ALLOWALL" always;
    }
  }
}
